export enum EActionTypes {
  // GET USERS
  GET_USERS_REQUEST = 'GET_USERS_REQUEST',
  GET_USERS_SUCCESS = 'GET_USERS_SUCCESS',
  GET_USERS_ERROR = 'GET_USERS_ERROR',
  SET_USERS_PAGINATION = 'SET_USERS_PAGINATION',

  // GET USER POSITIONS
  GET_USER_POSITION_REQUEST = 'GET_USER_POSITION_REQUEST',
  GET_USER_POSITION_SUCCESS = 'GET_USER_POSITION_SUCCESS',
  GET_USER_POSITION_ERROR = 'GET_USER_POSITION_ERROR',

  // GET TOKEN
  GET_USER_TOKEN_REQUEST = 'GET_USER_TOKEN_REQUEST',
  GET_USER_TOKEN_SUCCESS = 'GET_USER_TOKEN_SUCCESS',
  GET_USER_TOKEN_ERROR = 'GET_USER_TOKEN_ERROR',

  // POST USER REGISTER
  GET_USER_REGISTER_REQUEST = 'GET_USER_REGISTER_REQUEST',
  GET_USER_REGISTER_SUCCESS = 'GET_USER_REGISTER_SUCCESS',
  GET_USER_REGISTER_ERROR = 'GET_USER_REGISTER_ERROR',
}

